### ISSUE TITLE
RoR group project: set up the Kanban board

### ISSUE THREAD

**Issue by didierganthier** [didierganthier/recipe-app#11]
## Checklist
- [x] I have read this repository's contribution guidelines.
- [x] My issue has a descriptive title (not a vague title like Update index.MD)
- [x] My issue is linked to this [project](https://github.com/didierganthier/recipe-app).

## Summary
This issue shows the setup of the Kanban board for the Ruby on Rails project. And includes a link to the project. It can be found [here](https://github.com/users/didierganthier/projects/6)

 ## What changes have been made?
- [x] Create the Kanban board
- [x] Add the different project requirements as tasks
- [x] Estimate time needed for each tasks
- [x] Assign tasks to team members  

## Team Members
- @didierganthier
- @MarcoOquendoC

**Comment by KayLemba** [comment]
[# STATUS: APPROVED :green_circle: :clap: 

Hello  @didierganthier @MarcoOquendoC   , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: aaa
Congratulations! 🎉 

HIGHLIGHTS:

- [x]  Your repo is professional 
- [x] Descriptive P.R








 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]
